version: "3"

services:
  db_chat:
    image: postgres
    container_name: db_chat
    volumes:
      - db_chat_vol:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5488:5488"
  api:
    build: ./
    container_name: fatcode_chat
    image: fast-test
    command: "uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8010"
    ports:
      - 8010:8010
    volumes:
      - ./:/app
    depends_on:
      - db_chat
    env_file:
      - .env
volumes:
  db_chat_vol: